name: africas_talking
description: This package wraps Airtime, Sms, and Voice call from Africa's Talking APIs.
version: 0.0.1
# homepage: https://www.example.com
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  
dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
